name: test-gpu
on: [push]
jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: nvidia
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK > report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md
          cml-send-comment report.md
