name: train-relatio
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      env: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: nvidia
      run: |
        CODEBLOCK="\`\`\`"
        echo $CODEBLOCK > report.md
        nvidia-smi >> report.md
        echo $CODEBLOCK >> report.md
        cml-send-comment report.md
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start Training
      run: |
        python main.py
      uses: actions/upload-artifact@v3
      with:
        name: html-artifact
        path: persian-twitter.html
