name: train-relatio
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      env: 
        repo_token: ${{ secrets.GITHUB_TOKEN }}
    - name: nvidia
      run: |
        CODEBLOCK="\`\`\`"
        echo $CODEBLOCK > report.md
        nvidia-smi >> report.md
        echo $CODEBLOCK >> report.md
        cml-send-comment report.md
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Start Training
      run: |
        python main.py
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: html-artifact
        path: persian-twitter.html
